Repository AY2021S2-CS2113-F10-2/tp, pull requests merged in 2021-03, with the labels that each got.

#23 H-13: Add constructor to Record class.
  src/main/java/seedu/duke/record/Record.java
Labels: severity.High, type.Task

#25 H-13: Add classes FitCenter, User, RecordList, etc.
  src/main/java/seedu/duke/account/FitCenter.java
  src/main/java/seedu/duke/account/Gender.java
  src/main/java/seedu/duke/account/User.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/record/RecordList.java
  src/main/java/seedu/duke/record/comparator/RecordDateComparator.java
  src/main/java/seedu/duke/ui/UI.java
Labels: priority.High, type.Task

#24 H-14: Add functional driver classes for the app
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/CommandRecordType.java
  src/main/java/seedu/duke/command/CommandResult.java
  src/main/java/seedu/duke/command/CommandType.java
  src/main/java/seedu/duke/command/InvalidCommand.java
  src/main/java/seedu/duke/command/ViewCommand.java
  src/main/java/seedu/duke/commandparser/CommandParser.java
  src/main/java/seedu/duke/ui/UI.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Task

#33 H-15: Rename Duke as Healthier
  build.gradle
  src/main/java/seedu/duke/Healthier.java
  src/test/java/seedu/duke/HealthierTest.java
Labels: priority.Medium, type.Task

#36 H-14: update view command
  src/main/java/seedu/duke/command/ViewCommand.java
  src/main/java/seedu/duke/commandparser/CommandParser.java
Labels: priority.High, type.Task

#35 H-16: Optimize code & integration with FitCenter
  src/main/java/seedu/duke/Healthier.java
  src/main/java/seedu/duke/account/User.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/CommandResult.java
  src/main/java/seedu/duke/command/ExitCommand.java
  src/main/java/seedu/duke/command/InvalidCommand.java
  src/main/java/seedu/duke/command/ViewCommand.java
  src/main/java/seedu/duke/commandparser/CommandParser.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/ui/UI.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Task

#37 H-16: Minor UI bugfix
  src/main/java/seedu/duke/ui/UI.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium, type.Bug

#29 H-8: Create bodyWeight class
  src/main/java/seedu/duke/record/BodyWeight.java
  src/main/java/seedu/duke/record/Diet.java
  src/main/java/seedu/duke/record/Food.java
  src/main/java/seedu/duke/record/FoodCategory.java
Labels: priority.High, type.Story

#39 H-16: Integrate View Command & various bugfix
  src/main/java/seedu/duke/Healthier.java
  src/main/java/seedu/duke/account/FitCenter.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/CommandRecordType.java
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/command/ExitCommand.java
  src/main/java/seedu/duke/command/InvalidCommand.java
  src/main/java/seedu/duke/command/ViewCommand.java
  src/main/java/seedu/duke/commandparser/CommandParser.java
  src/main/java/seedu/duke/record/RecordList.java
Labels: priority.High, type.Task

#43 V1.0
  src/main/java/seedu/duke/account/FitCenter.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/commandparser/CommandParser.java
  src/main/java/seedu/duke/exception/TypeException.java
  src/main/java/seedu/duke/record/Diet.java
  src/main/java/seedu/duke/record/FoodCategory.java
  src/main/java/seedu/duke/record/Record.java
Labels: priority.High, type.Story

#44 H-16: parser and command bug fix
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/command/InvalidCommand.java
  src/main/java/seedu/duke/commandparser/CommandParser.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/ui/UI.java
Labels: priority.High, type.Task

#45 H-16: bugfix & code integration & cleanup
  src/main/java/seedu/duke/Healthier.java
  src/main/java/seedu/duke/account/FitCenter.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/InvalidCommand.java
  src/main/java/seedu/duke/command/ViewCommand.java
  src/main/java/seedu/duke/commandparser/CommandParser.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/exception/TypeException.java
  src/main/java/seedu/duke/record/BodyWeight.java
  src/main/java/seedu/duke/record/Diet.java
  src/main/java/seedu/duke/record/Exercise.java
  src/main/java/seedu/duke/record/Food.java
  src/main/java/seedu/duke/record/FoodCategory.java
  src/main/java/seedu/duke/record/RecordList.java
  src/main/java/seedu/duke/record/Sleep.java
  src/main/java/seedu/duke/record/WorkOutCategory.java
  src/main/java/seedu/duke/record/Workout.java
  src/main/java/seedu/duke/record/WorkoutCategory.java
  src/main/java/seedu/duke/ui/UI.java
Labels: severity.High, type.Task

#46 H-16: Update view result
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/ViewCommand.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/record/BodyWeight.java
  src/main/java/seedu/duke/record/Diet.java
  src/main/java/seedu/duke/record/Exercise.java
  src/main/java/seedu/duke/record/Record.java
  src/main/java/seedu/duke/record/RecordList.java
  src/main/java/seedu/duke/record/Sleep.java
  src/main/java/seedu/duke/ui/UI.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Task

#49 Update UserGuide
  docs/UserGuide.md
Labels: priority.Medium, type.Task

#50 H-16: add Junit test for FitCenter & RecordList.
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/test/java/seedu/duke/account/FitCenterTest.java
  src/test/java/seedu/duke/record/RecordListTest.java
Labels: priority.High, type.Task

#48 V1.0 bug fix
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/commandparser/CommandParser.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/record/RecordList.java
  src/test/java/seedu/duke/command/AddCommandTest.java
  src/test/java/seedu/duke/command/DeleteCommandTest.java
  src/test/java/seedu/duke/command/ViewCommandTest.java
Labels: severity.High, type.Bug, type.Task

#53 H-17: Update build.gradle to enable assertions.
  build.gradle
Labels: priority.High, type.Task

#57 update file handler
  data/records.txt
  src/main/java/seedu/duke/Healthier.java
  src/main/java/seedu/duke/account/FitCenter.java
  src/main/java/seedu/duke/record/BodyWeight.java
  src/main/java/seedu/duke/record/Diet.java
  src/main/java/seedu/duke/record/Exercise.java
  src/main/java/seedu/duke/record/Record.java
  src/main/java/seedu/duke/record/RecordList.java
  src/main/java/seedu/duke/record/Sleep.java
  src/main/java/seedu/duke/storage/FileReader.java
  src/main/java/seedu/duke/storage/FileWriter.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/ui/UI.java
Labels: priority.High, type.Task

#59 Update DietGoal
  src/main/java/seedu/duke/account/FitCenter.java
  src/main/java/seedu/duke/goal/DietGoal.java
Labels: priority.High, type.Story

#58 Goal ruiqian
  src/main/java/seedu/duke/account/FitCenter.java
  src/main/java/seedu/duke/goal/BodyWeightGoal.java
  src/main/java/seedu/duke/goal/SleepGoal.java
Labels: priority.High, type.Story

#63 H-9,10,11,12: Add Goal features
  data/records.txt
  src/main/java/seedu/duke/account/FitCenter.java
  src/main/java/seedu/duke/command/CancelCommand.java
  src/main/java/seedu/duke/command/CheckCommand.java
  src/main/java/seedu/duke/command/CommandRecordType.java
  src/main/java/seedu/duke/command/CommandType.java
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/command/InvalidCommand.java
  src/main/java/seedu/duke/command/SetCommand.java
  src/main/java/seedu/duke/commandparser/CommandParser.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/goal/BodyWeightGoal.java
  src/main/java/seedu/duke/goal/DietGoal.java
  src/main/java/seedu/duke/goal/ExerciseGoal.java
  src/main/java/seedu/duke/goal/Goal.java
  src/main/java/seedu/duke/goal/GoalList.java
  src/main/java/seedu/duke/goal/PeriodType.java
  src/main/java/seedu/duke/goal/SleepGoal.java
  src/main/java/seedu/duke/record/BodyWeight.java
  src/main/java/seedu/duke/record/Diet.java
  src/main/java/seedu/duke/record/Exercise.java
  src/main/java/seedu/duke/record/Record.java
  src/main/java/seedu/duke/record/Sleep.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Story

#70 H-Doc: update doc index
  docs/DeveloperGuide.md
Labels: documentation, priority.High, type.Task

#69 H-18: Add time controller for initializing goal progress
  data/appTime.txt
  src/main/java/seedu/duke/Healthier.java
  src/main/java/seedu/duke/account/FitCenter.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/goal/ExerciseGoal.java
  src/main/java/seedu/duke/goal/Goal.java
  src/main/java/seedu/duke/goal/GoalList.java
  src/main/java/seedu/duke/goal/timemanager/TimeController.java
  src/main/java/seedu/duke/storage/FileInfoReader.java
  src/main/java/seedu/duke/storage/FileInfoWriter.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/ui/UI.java
Labels: priority.High, type.Story, type.Task
