Repository AY2021S2-CS2113-F10-2/tp, pull requests merged in 2021-04, with the labels that each got.

#72 H-18: Add Weekly progress update logic & goal prompt message
  data/goals.txt
  data/records.txt
  src/main/java/seedu/duke/Healthier.java
  src/main/java/seedu/duke/account/FitCenter.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/goal/BodyWeightGoal.java
  src/main/java/seedu/duke/goal/DietGoal.java
  src/main/java/seedu/duke/goal/ExerciseGoal.java
  src/main/java/seedu/duke/goal/Goal.java
  src/main/java/seedu/duke/goal/GoalList.java
  src/main/java/seedu/duke/goal/SleepGoal.java
  src/main/java/seedu/duke/goal/timemanager/TimeController.java
  src/main/java/seedu/duke/record/Diet.java
  src/main/java/seedu/duke/record/RecordList.java
  src/main/java/seedu/duke/storage/FileInfoReader.java
  src/main/java/seedu/duke/ui/UI.java
  src/test/META-INF/MANIFEST.MF
Labels: priority.High, type.Enhancement, type.Task

#73 fix display format
  data/appTime.txt
  docs/DeveloperGuide.md
  docs/diagrams/AddRecord.puml
  docs/diagrams/try.puml
  src/main/java/seedu/duke/command/SetCommand.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/goal/BodyWeightGoal.java
  src/main/java/seedu/duke/goal/DietGoal.java
  src/main/java/seedu/duke/goal/ExerciseGoal.java
  src/main/java/seedu/duke/goal/Goal.java
  src/main/java/seedu/duke/goal/SleepGoal.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Task

#74 H-18: Add Weekly progress update logic & goal prompt message
  src/main/java/seedu/duke/Healthier.java
  src/main/java/seedu/duke/account/FitCenter.java
  src/main/java/seedu/duke/goal/BodyWeightGoal.java
  src/main/java/seedu/duke/goal/DietGoal.java
  src/main/java/seedu/duke/goal/ExerciseGoal.java
  src/main/java/seedu/duke/goal/Goal.java
  src/main/java/seedu/duke/goal/GoalList.java
  src/main/java/seedu/duke/goal/PeriodType.java
  src/main/java/seedu/duke/goal/SleepGoal.java
  src/main/java/seedu/duke/goal/timemanager/TimeController.java
  src/main/java/seedu/duke/storage/FileInfoReader.java
  src/main/java/seedu/duke/storage/FileInfoWriter.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/ui/UI.java
Labels: priority.High, type.Task

#78 H-nameFix: update the naming of "period type" to "interval type"
  docs/UserGuide.md
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/commandparser/CommandParser.java
  src/main/java/seedu/duke/common/Messages.java
Labels: enhancement, priority.Medium, severity.Medium, type.Enhancement

#80 H-fix: minor bug fix for goal command & display issue
  src/main/java/seedu/duke/commandparser/CommandParser.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/goal/BodyWeightGoal.java
  src/main/java/seedu/duke/goal/DietGoal.java
  src/main/java/seedu/duke/goal/ExerciseGoal.java
  src/main/java/seedu/duke/goal/Goal.java
  src/main/java/seedu/duke/goal/GoalList.java
  src/main/java/seedu/duke/goal/SleepGoal.java
Labels: priority.High, severity.High, type.Bug

#82 H-mfix2: minor bugfix for goal prompt
  src/main/java/seedu/duke/account/FitCenter.java
  src/main/java/seedu/duke/goal/Goal.java
Labels: priority.High, severity.High, type.Bug

#129 H-docFix: fix bugs & typos in UserGuide.md
  docs/UserGuide.md
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/record/Diet.java
Labels: priority.Medium, severity.Medium, type.Bug

#136 H-gsfix: add bugfix for weekly sleep goal target duration
  src/main/java/seedu/duke/commandparser/CommandParser.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/goal/SleepGoal.java
Labels: priority.High, severity.High, type.Bug

#137 H-paraFix: Add handling of redundant parameters.
  docs/UserGuide.md
  src/main/java/seedu/duke/commandparser/CommandParser.java
  src/main/java/seedu/duke/goal/BodyWeightGoal.java
  src/main/java/seedu/duke/goal/DietGoal.java
  src/main/java/seedu/duke/goal/ExerciseGoal.java
  src/main/java/seedu/duke/goal/Goal.java
  src/main/java/seedu/duke/goal/SleepGoal.java
Labels: priority.High, severity.High, type.Bug

#138 H-inFix: Change the naming of period type to interval type
  data/appTime.txt
  src/main/java/seedu/duke/account/FitCenter.java
  src/main/java/seedu/duke/command/CheckCommand.java
  src/main/java/seedu/duke/command/SetCommand.java
  src/main/java/seedu/duke/commandparser/CommandParser.java
  src/main/java/seedu/duke/goal/BodyWeightGoal.java
  src/main/java/seedu/duke/goal/DietGoal.java
  src/main/java/seedu/duke/goal/ExerciseGoal.java
  src/main/java/seedu/duke/goal/Goal.java
  src/main/java/seedu/duke/goal/GoalList.java
  src/main/java/seedu/duke/goal/IntervalType.java
  src/main/java/seedu/duke/goal/PeriodType.java
  src/main/java/seedu/duke/goal/SleepGoal.java
  src/main/java/seedu/duke/goal/comparator/GoalIntervalTypeComparator.java
  src/main/java/seedu/duke/goal/timemanager/TimeController.java
  src/main/java/seedu/duke/storage/FileInfoReader.java
Labels: priority.Low, severity.Low, type.Enhancement

#139 H-acFix: update logic of isGoalAchieved method.
  src/main/java/seedu/duke/account/FitCenter.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/goal/BodyWeightGoal.java
Labels: priority.High, severity.High, type.Bug

#135 fix bugs for view command
  src/main/java/seedu/duke/commandparser/CommandParser.java
Labels: priority.Medium, severity.Medium, type.Bug

#142 H-dg: update Developer Guide (Design-architecture & Appendix)
  docs/DeveloperGuide.md
  docs/diagrams/DG_Images/architecture.png
  docs/diagrams/DG_Images/handleUserInput.png
Labels: documentation, priority.High, type.Enhancement, type.Task

#149 H-dg2: add components & implementation of setCommand.
  docs/DeveloperGuide.md
  docs/diagrams/DG_Images/SetCommand.png
Labels: documentation, priority.High, type.Enhancement, type.Task

#152 H-ppp: Add ppp, minor fix for README.md & user guide
  docs/AboutUs.md
  docs/README.md
  docs/UserGuide.md
  docs/team/song0180.md
Labels: documentation, priority.High, type.Task
